name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx furo myst_parser sphinx-intl
      - name: Sphinx build
        run: |
          sphinx-build doc _build/ru -D language=ru
          sphinx-build doc _build/en -D language=en
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages  # Ветка для GitHub Pages
          folder: _build  # Папка с собранным проектом
